### PR TITLE
Upstream `freetype2` version upgrade 2.6.3

### PR DESCRIPTION
**Pull request by renatoaguiar**

### CODE REVIEW

**Comment by perfect7gentleman** [comment]
your 02-patch has already contained 01-patch.
please, correct it.

**Comment by renatoaguiar** [comment]
It has been fixed already. It was broken on pull request #135.

**Comment by perfect7gentleman** [comment]
thanx

**Comment by bohoomil** [comment]
@renatoaguiar Thank you so much for taking care of the upgrade. I will be back soon and will do my job as usual.

**Comment by lockie** [comment]
Hello!
Do you mind merging this?

**Comment by onodera-punpun** [comment]
It seems like this has been merged.

**Comment by bohoomil** [comment]
I updated the Infinality patch and made it work with the recent upstream commits. Everything is working fine, the binaries will be available once I'm done with other packages.

**Pull request closed without merging**
