### PR TITLE
Upstream source compatibility improvements

### PR DESCRIPTION
**Pull request by goddesse**
*Build with _GNU_SOURCE for strcasestr and strcasecmp
*Use freetype2's new header file macros where possible

### CODE REVIEW

**Comment by bohoomil** [comment]
Thank you very much!

**Comment by goddesse** [comment]
Is #98 still a problem for you with this build? If so, can you point me to an SVG that crashes still?

**Comment by bohoomil** [comment]
Unfortunately, yes, nautilus still crashes with SVG files. I used the one provided in #81, [Keller-Raumschild.svg](https://dl.dropboxusercontent.com/u/44720989/Keller-Raumschild.svg), for tests.

BTW, nemo is also affected.

**Comment by goddesse** [comment]
Well, that's a bit unfortunate. I can install an older release on Fedora 22 that wasn't built with _GNU_SOURCE and immediately get the crash, but once I install the most recent package and login again to make sure the new freetype-infinality is loaded, I can no longer repro the crash.

I'll install Arch in a virtual machine later this evening and hopefully I can repro it. Can you look through the build output and see if you're getting complaints about an implicit strcasecmp and strcasestr from GCC?

**Comment by bohoomil** [comment]
No: strcasecmp and strcasestr complaints appeared in the previous build(s), before I applied your patches.

**Comment by vcunat** [comment]
This caused me problems when compiling for windows, as there's apparently no `strcasestr` available. (Details: I'm cross-compiling linux->mingw.)

**Comment by vcunat** [comment]
Perhaps it would be better to use standard functions instead. But personally this edge case of mingw+infinality isn't important to me; I just stumbled on it and avoided it by not using infinality.

**Pull request merged**
